services:
  - type: web
    name: wardex-backend
    env: node
    region: oregon
    plan: free
    buildCommand: rm -rf node_modules && npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.20.0
      - key: NPM_VERSION
        value: 10.5.0
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_CACHE
        value: /tmp/npm-cache
